import type { FrameConfig } from './types';
import { PALETTE } from './palette';
import { deco, frame, slot, text } from './builders';

// Canvas bases (logical px, exported at 2x+ for print).
const PORTRAIT = { w: 1200, h: 1500 };
const SQUARE = { w: 1200, h: 1200 };
const LANDSCAPE = { w: 1500, h: 1000 };
const STORY = { w: 1080, h: 1920 };
const STRIP = { w: 700, h: 2100 };

export const FRAME_PRESETS: FrameConfig[] = [
  // 1. Y & I Signature — SIGNATURE
  frame({
    slug: 'y-i-signature',
    name: 'Y & I Signature',
    category: 'signature',
    description: 'Ivory minimal dengan monogram dan tanggal pernikahan.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(80, 90, 1040, 1160, { radius: 6 })],
    texts: [
      text('{{monogram}}', 600, 1310, 40, { role: 'display', color: PALETTE.bronze, letterSpacing: 4 }),
      text('{{couple}}', 600, 1375, 26, { role: 'label', color: PALETTE.ink, letterSpacing: 2 }),
      text('{{date}}', 600, 1420, 16, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 2. Better Together — SIGNATURE
  frame({
    slug: 'better-together',
    name: 'Better Together',
    category: 'signature',
    description: 'Kutipan "Better Together" dengan nama pasangan.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.cream,
    accentColor: PALETTE.ink,
    photoSlots: [slot(70, 70, 1060, 1230, { radius: 6 })],
    texts: [
      text('BETTER TOGETHER', 600, 1355, 34, { role: 'label', letterSpacing: 6, color: PALETTE.ink }),
      text('{{couple}}', 600, 1378, 22, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [deco('double-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 3. Botanical Ivory — FLORAL
  frame({
    slug: 'botanical-ivory',
    name: 'Botanical Ivory',
    category: 'floral',
    description: 'Elemen floral lembut di setiap sudut.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.sage,
    photoSlots: [slot(80, 80, 1040, 1200)],
    texts: [text('{{couple}}', 600, 1390, 26, { role: 'display', color: PALETTE.inkSoft })],
    decorations: [deco('floral-corner', { placement: ['all'] })],
    enabled: true,
  }),

  // 4. Garden Romance — FLORAL
  frame({
    slug: 'garden-romance',
    name: 'Garden Romance',
    category: 'floral',
    description: 'Border bunga romantis di atas dan bawah.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.blush,
    accentColor: PALETTE.rose,
    photoSlots: [slot(90, 210, 1020, 1080)],
    texts: [text('{{couple}}', 600, 130, 32, { role: 'script', color: PALETTE.ink })],
    decorations: [deco('floral-border', { placement: ['top', 'bottom'] })],
    enabled: true,
  }),

  // 5. Editorial Wedding — EDITORIAL
  frame({
    slug: 'editorial-wedding',
    name: 'Editorial Wedding',
    category: 'editorial',
    description: 'Gaya majalah pernikahan dengan kop editorial.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.ink,
    photoSlots: [slot(70, 230, 1060, 1190, { radius: 4 })],
    texts: [
      text('THE WEDDING OF', 600, 80, 20, { role: 'label', letterSpacing: 6, color: PALETTE.inkSoft }),
      text('{{couple}}', 600, 150, 48, { role: 'display', color: PALETTE.ink }),
    ],
    decorations: [deco('newspaper-rule')],
    enabled: true,
  }),

  // 6. Modern Minimal — MINIMAL
  frame({
    slug: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'minimal',
    description: 'Border tipis dan bersih tanpa ornamen berlebih.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [slot(48, 48, 1104, 1330, { radius: 2 })],
    texts: [text('{{couple}}', 600, 1440, 20, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 })],
    decorations: [],
    enabled: true,
  }),

  // 7. Classic Monogram — SIGNATURE
  frame({
    slug: 'classic-monogram',
    name: 'Classic Monogram',
    category: 'signature',
    description: 'Monogram Y & I besar di atas foto.',
    orientation: 'square',
    photoCount: 1,
    canvasWidth: SQUARE.w,
    canvasHeight: SQUARE.h,
    backgroundColor: PALETTE.cream,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(80, 260, 1040, 860, { radius: 6 })],
    texts: [text('{{couple}}', 600, 1170, 22, { role: 'label', color: PALETTE.inkSoft, letterSpacing: 3 })],
    decorations: [deco('monogram-badge', { placement: ['top'] })],
    enabled: true,
  }),

  // 8. Our Forever — SIGNATURE
  frame({
    slug: 'our-forever',
    name: 'Our Forever',
    category: 'signature',
    description: '"Our Forever Starts Here" di bawah foto.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.rose,
    photoSlots: [slot(80, 80, 1040, 1220, { radius: 6 })],
    texts: [text('OUR FOREVER STARTS HERE', 600, 1370, 24, { role: 'label', letterSpacing: 3, color: PALETTE.rose })],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 9. Polaroid Love — POLAROID
  frame({
    slug: 'polaroid-love',
    name: 'Polaroid Love',
    category: 'polaroid',
    description: 'Layout Polaroid premium dengan tulisan tangan.',
    orientation: 'square',
    photoCount: 1,
    canvasWidth: SQUARE.w,
    canvasHeight: 1360,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [slot(60, 60, 1080, 1080, { radius: 0 })],
    texts: [text('{{couple}} · {{date}}', 600, 1240, 30, { role: 'script', color: PALETTE.ink })],
    decorations: [deco('polaroid-tab')],
    enabled: true,
  }),

  // 10. Film Memories — CLASSIC
  frame({
    slug: 'film-memories',
    name: 'Film Memories',
    category: 'classic',
    description: 'Border bergaya film dengan sprocket di kedua sisi.',
    orientation: 'landscape',
    photoCount: 1,
    canvasWidth: LANDSCAPE.w,
    canvasHeight: LANDSCAPE.h,
    backgroundColor: PALETTE.charcoal,
    accentColor: PALETTE.charcoalText,
    photoSlots: [slot(90, 60, 1320, 830, { radius: 0 })],
    texts: [text('{{couple}} — {{date}}', 750, 950, 20, { role: 'mono', color: PALETTE.charcoalText, letterSpacing: 3 })],
    decorations: [deco('film-sprockets')],
    enabled: true,
  }),

  // 11. Classic Photo Strip — PHOTO STRIP
  frame({
    slug: 'classic-photo-strip',
    name: 'Classic Photo Strip',
    category: 'strip',
    description: 'Strip vertikal 3 foto klasik.',
    orientation: 'strip',
    photoCount: 3,
    canvasWidth: STRIP.w,
    canvasHeight: STRIP.h,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(40, 40, 620, 620, { radius: 4 }),
      slot(40, 690, 620, 620, { radius: 4 }),
      slot(40, 1340, 620, 620, { radius: 4 }),
    ],
    texts: [text('{{couple}} · {{date}}', 350, 2015, 20, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 })],
    decorations: [],
    enabled: true,
  }),

  // 12. Floral Photo Strip — PHOTO STRIP
  frame({
    slug: 'floral-photo-strip',
    name: 'Floral Photo Strip',
    category: 'strip',
    description: 'Strip 3 foto dengan detail floral lembut.',
    orientation: 'strip',
    photoCount: 3,
    canvasWidth: STRIP.w,
    canvasHeight: STRIP.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.sage,
    photoSlots: [
      slot(50, 60, 600, 600, { radius: 6 }),
      slot(50, 710, 600, 600, { radius: 6 }),
      slot(50, 1360, 600, 600, { radius: 6 }),
    ],
    texts: [text('{{monogram}}', 350, 2010, 26, { role: 'display', color: PALETTE.sage, letterSpacing: 3 })],
    decorations: [deco('floral-corner', { placement: ['top-left', 'bottom-right'] })],
    enabled: true,
  }),

  // 13. Four Moments — GROUP (2x2 grid)
  frame({
    slug: 'four-moments',
    name: 'Four Moments',
    category: 'group',
    description: 'Layout grid 2×2 untuk empat momen.',
    orientation: 'square',
    photoCount: 4,
    canvasWidth: SQUARE.w,
    canvasHeight: 1320,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(50, 50, 545, 545, { radius: 6 }),
      slot(605, 50, 545, 545, { radius: 6 }),
      slot(50, 605, 545, 545, { radius: 6 }),
      slot(605, 605, 545, 545, { radius: 6 }),
    ],
    texts: [text('{{couple}} · {{date}}', 600, 1230, 22, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 })],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 14. Two of Us — GROUP
  frame({
    slug: 'two-of-us',
    name: 'Two of Us',
    category: 'group',
    description: 'Dua foto berdampingan untuk pasangan.',
    orientation: 'portrait',
    photoCount: 2,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.cream,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(70, 80, 1060, 560, { radius: 6 }), slot(70, 660, 1060, 560, { radius: 6 })],
    texts: [text('TWO OF US', 600, 1370, 26, { role: 'label', letterSpacing: 5, color: PALETTE.bronze })],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 15. Family Portrait — GROUP
  frame({
    slug: 'family-portrait',
    name: 'Family Portrait',
    category: 'group',
    description: 'Layout lebar untuk foto keluarga/rombongan.',
    orientation: 'landscape',
    photoCount: 1,
    canvasWidth: LANDSCAPE.w,
    canvasHeight: LANDSCAPE.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(70, 70, 1360, 780, { radius: 6 })],
    texts: [text('{{couple}}', 750, 920, 30, { role: 'display', color: PALETTE.ink })],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 16. Wedding Newspaper — EDITORIAL
  frame({
    slug: 'wedding-newspaper',
    name: 'Wedding Newspaper',
    category: 'editorial',
    description: 'Masthead ala koran untuk "The Wedding Edition".',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [slot(70, 220, 1060, 1150, { radius: 0 })],
    texts: [
      text('THE WEDDING EDITION', 600, 80, 22, { role: 'label', letterSpacing: 5, color: PALETTE.inkSoft }),
      text('{{couple}}', 600, 155, 44, { role: 'display', color: PALETTE.ink }),
    ],
    decorations: [deco('newspaper-rule')],
    enabled: true,
  }),

  // 17. Save The Memory — CLASSIC
  frame({
    slug: 'save-the-memory',
    name: 'Save The Memory',
    category: 'classic',
    description: 'Caption "Save The Memory" yang sederhana.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.parchment,
    accentColor: PALETTE.ink,
    photoSlots: [slot(80, 80, 1040, 1210, { radius: 8 })],
    texts: [text('SAVE THE MEMORY', 600, 1360, 26, { role: 'label', letterSpacing: 4, color: PALETTE.ink })],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 18. Love in Bloom — FLORAL
  frame({
    slug: 'love-in-bloom',
    name: 'Love in Bloom',
    category: 'floral',
    description: 'Bingkai floral lembut dengan aksen sage.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.sage,
    photoSlots: [slot(90, 150, 1020, 1140)],
    texts: [text('{{couple}}', 600, 1400, 24, { role: 'script', color: PALETTE.sage })],
    decorations: [deco('floral-corner', { placement: ['top-left', 'top-right'] })],
    enabled: true,
  }),

  // 19. Clean White — MINIMAL
  frame({
    slug: 'clean-white',
    name: 'Clean White',
    category: 'minimal',
    description: 'Frame ultra-minim, hanya foto dan sedikit ruang.',
    orientation: 'square',
    photoCount: 1,
    canvasWidth: SQUARE.w,
    canvasHeight: SQUARE.h,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.inkSoft,
    photoSlots: [slot(40, 40, 1120, 1120, { radius: 4 })],
    texts: [],
    decorations: [],
    enabled: true,
  }),

  // 20. Evening Reception — DARK
  frame({
    slug: 'evening-reception',
    name: 'Evening Reception',
    category: 'dark',
    description: 'Bingkai gelap elegan untuk sesi resepsi malam.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.charcoal,
    accentColor: PALETTE.gold,
    photoSlots: [slot(80, 90, 1040, 1160, { radius: 6 })],
    texts: [
      text('{{couple}}', 600, 1310, 32, { role: 'display', color: PALETTE.gold }),
      text('{{date}}', 600, 1360, 16, { role: 'mono', color: PALETTE.charcoalText }),
    ],
    decorations: [deco('dark-vignette'), deco('gold-corner')],
    enabled: true,
  }),

  // 21. Vintage Postcard — CLASSIC
  frame({
    slug: 'vintage-postcard',
    name: 'Vintage Postcard',
    category: 'classic',
    description: 'Terinspirasi kartu pos pernikahan klasik.',
    orientation: 'landscape',
    photoCount: 1,
    canvasWidth: LANDSCAPE.w,
    canvasHeight: LANDSCAPE.h,
    backgroundColor: PALETTE.parchment,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(60, 60, 1380, 830, { radius: 2 })],
    texts: [text('{{couple}} · {{date}}', 750, 940, 22, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 })],
    decorations: [deco('double-rule', { placement: ['bottom'] }), deco('gold-corner', { placement: ['top-right'] })],
    enabled: true,
  }),

  // 22. Film Contact Sheet — EDITORIAL (4 shots)
  frame({
    slug: 'film-contact-sheet',
    name: 'Film Contact Sheet',
    category: 'editorial',
    description: 'Empat bingkai kecil ala lembar kontak film.',
    orientation: 'landscape',
    photoCount: 4,
    canvasWidth: 1800,
    canvasHeight: 900,
    backgroundColor: PALETTE.charcoal,
    accentColor: PALETTE.charcoalText,
    photoSlots: [
      slot(80, 120, 380, 660, { radius: 0 }),
      slot(500, 120, 380, 660, { radius: 0 }),
      slot(920, 120, 380, 660, { radius: 0 }),
      slot(1340, 120, 380, 660, { radius: 0 }),
    ],
    texts: [text('{{couple}} — {{date}}', 900, 60, 22, { role: 'mono', color: PALETTE.charcoalText, letterSpacing: 4 })],
    decorations: [deco('film-sprockets')],
    enabled: true,
  }),

  // 23. Monogram Gold — SIGNATURE
  frame({
    slug: 'monogram-gold',
    name: 'Monogram Gold',
    category: 'signature',
    description: 'Monogram emas elegan di atas foto.',
    orientation: 'square',
    photoCount: 1,
    canvasWidth: SQUARE.w,
    canvasHeight: SQUARE.h,
    backgroundColor: PALETTE.ink,
    accentColor: PALETTE.gold,
    photoSlots: [slot(80, 260, 1040, 860, { radius: 6 })],
    texts: [text('{{couple}}', 600, 1170, 22, { role: 'label', color: PALETTE.gold, letterSpacing: 3 })],
    decorations: [deco('monogram-badge', { placement: ['top'] })],
    enabled: true,
  }),

  // 24. Story Frame — SIGNATURE (9:16)
  frame({
    slug: 'story-frame',
    name: 'Story Frame',
    category: 'signature',
    description: 'Format 9:16 untuk dibagikan ke Instagram Story.',
    orientation: 'story',
    photoCount: 1,
    canvasWidth: STORY.w,
    canvasHeight: STORY.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(60, 260, 960, 1200, { radius: 8 })],
    texts: [
      text('{{couple}}', 540, 1560, 40, { role: 'display', color: PALETTE.ink }),
      text('{{hashtag}}', 540, 1620, 22, { role: 'mono', color: PALETTE.bronze }),
    ],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 25. Our Day — MINIMAL / EDITORIAL
  frame({
    slug: 'our-day',
    name: 'Our Day',
    category: 'minimal',
    description: 'Caption editorial sederhana "Our Day".',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.ink,
    photoSlots: [slot(90, 90, 1020, 1180, { radius: 6 })],
    texts: [
      text('OUR DAY', 600, 1340, 22, { role: 'label', letterSpacing: 6, color: PALETTE.inkSoft }),
      text('{{date}}', 600, 1390, 16, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 26. Magazine Cover — EDITORIAL
  frame({
    slug: 'magazine-cover',
    name: 'Magazine Cover',
    category: 'editorial',
    description: 'Sampul majalah pernikahan lengkap dengan masthead dan barcode.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [slot(0, 170, 1200, 1330, { radius: 0 })],
    texts: [text('{{date}}', 140, 1440, 16, { role: 'mono', color: '#FFFFFF', align: 'left' })],
    decorations: [
      deco('magazine-masthead', { text: 'Y & I', subtext: 'The Wedding Issue', layer: 'back' }),
      deco('barcode', { color: PALETTE.ink, layer: 'front' }),
    ],
    enabled: true,
  }),

  // 27. Comic Pop — FUN
  frame({
    slug: 'comic-pop',
    name: 'Comic Pop',
    category: 'fun',
    description: 'Gaya komik pop-art dengan halftone dan speech bubble.',
    orientation: 'square',
    photoCount: 1,
    canvasWidth: SQUARE.w,
    canvasHeight: SQUARE.h,
    backgroundColor: '#FFF7E8',
    accentColor: PALETTE.ink,
    photoSlots: [slot(60, 60, 1080, 1080, { radius: 8 })],
    texts: [],
    decorations: [
      deco('halftone-dots', { placement: ['bottom'], color: PALETTE.rose, layer: 'back' }),
      deco('speech-bubble', { text: 'JUST MARRIED!', color: PALETTE.ink, layer: 'front' }),
      deco('comic-burst', { text: 'LOVE!', color: PALETTE.gold, placement: ['bottom-right'], layer: 'front' }),
    ],
    enabled: true,
  }),

  // 28. Newspaper Broadsheet — EDITORIAL / CLASSIC
  frame({
    slug: 'newspaper-broadsheet',
    name: 'Newspaper Broadsheet',
    category: 'editorial',
    description: 'Tata letak koran lengkap dengan kolom dan headline.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: '#F7F4EC',
    accentColor: PALETTE.ink,
    photoSlots: [slot(70, 240, 1060, 1030, { radius: 0 })],
    texts: [
      text('YUDHA & IMA GAZETTE', 600, 70, 24, { role: 'label', letterSpacing: 3, color: PALETTE.ink }),
      text('TWO BECOME ONE TODAY', 600, 175, 34, { role: 'display', color: PALETTE.ink }),
      text('{{date}} · {{hashtag}}', 600, 1420, 16, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 1 }),
    ],
    decorations: [deco('newspaper-rule', { layer: 'back' }), deco('newspaper-columns', { layer: 'back' })],
    enabled: true,
  }),

  // 29. Retro Sunset Strip — FUN / STRIP
  frame({
    slug: 'retro-sunset-strip',
    name: 'Retro Sunset Strip',
    category: 'fun',
    description: 'Strip 3 foto dengan sentuhan warna retro hangat.',
    orientation: 'strip',
    photoCount: 3,
    canvasWidth: STRIP.w,
    canvasHeight: STRIP.h,
    backgroundColor: '#3B2A2E',
    accentColor: PALETTE.gold,
    photoSlots: [
      slot(40, 40, 620, 620, { radius: 10 }),
      slot(40, 690, 620, 620, { radius: 10 }),
      slot(40, 1340, 620, 620, { radius: 10 }),
    ],
    texts: [text('{{couple}} · {{hashtag}}', 350, 2015, 20, { role: 'label', color: PALETTE.gold, letterSpacing: 2 })],
    decorations: [deco('gold-corner', { placement: ['top-left', 'bottom-right'] })],
    enabled: true,
  }),

  // 30. Boho Line Art — FLORAL
  frame({
    slug: 'boho-line-art',
    name: 'Boho Line Art',
    category: 'floral',
    description: 'Garis floral tipis bergaya boho minimalis.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: PORTRAIT.w,
    canvasHeight: PORTRAIT.h,
    backgroundColor: PALETTE.parchment,
    accentColor: PALETTE.bronze,
    photoSlots: [slot(100, 130, 1000, 1120, { radius: 4 })],
    texts: [text('{{couple}}', 600, 1370, 26, { role: 'script', color: PALETTE.bronze })],
    decorations: [deco('floral-border', { placement: ['top'] }), deco('thin-rule', { placement: ['bottom'] })],
    enabled: true,
  }),

  // 31. Wedding Gazette Cover — EDITORIAL (front-page newspaper style)
  frame({
    slug: 'wedding-gazette-cover',
    name: 'Wedding Gazette Cover',
    category: 'editorial',
    description: 'Halaman depan koran lengkap: masthead, kolom teks, dan dua foto.',
    orientation: 'portrait',
    photoCount: 2,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F8F5EC',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(280, 260, 640, 720, { radius: 0 }),
      slot(70, 1040, 280, 280, { radius: 0 }),
    ],
    texts: [
      text('TWO HEARTS, ONE STORY', 600, 1010, 26, { role: 'display', color: PALETTE.ink }),
      text('{{couple}} · {{date}}', 600, 1490, 16, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 1 }),
      text('SPECIAL EDITION', 600, 1530, 14, { role: 'label', color: PALETTE.inkSoft, letterSpacing: 4 }),
    ],
    decorations: [
      deco('newspaper-masthead-box', { text: '{{couple}} GAZETTE', subtext: 'Wedding Edition', layer: 'back' }),
      deco('body-copy', {
        text: 'Pada hari yang penuh bahagia ini, {{couple}} resmi mengucap janji suci di hadapan keluarga dan sahabat tercinta, mengawali babak baru dalam kisah cinta mereka.',
        x: 0.06,
        y: 0.175,
        width: 0.16,
        fontSize: 0.0125,
        lineHeight: 1.55,
        color: PALETTE.ink,
        layer: 'back',
      }),
      deco('body-copy', {
        text: 'Dengan restu kedua orang tua serta doa dari semua yang hadir, cinta ini akan terus tumbuh dan menjadi rumah bagi satu sama lain, hari ini dan selamanya.',
        x: 0.78,
        y: 0.175,
        width: 0.16,
        fontSize: 0.0125,
        lineHeight: 1.55,
        color: PALETTE.ink,
        layer: 'back',
      }),
      deco('body-copy', {
        text: '{{hashtag}} — abadikan momenmu bersama kami, lalu bagikan ceritamu di album bersama.',
        x: 0.4,
        y: 0.66,
        width: 0.54,
        fontSize: 0.013,
        lineHeight: 1.5,
        color: PALETTE.inkSoft,
        layer: 'back',
      }),
    ],
    enabled: true,
  }),

  // 32. Headline Love Story — EDITORIAL (bold single headline, like a daily cover)
  frame({
    slug: 'headline-love-story',
    name: 'Headline Love Story',
    category: 'editorial',
    description: 'Judul besar ala cover majalah harian di bawah foto.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [slot(60, 170, 1080, 900, { radius: 4 })],
    texts: [
      text('YOU ARE WORTHY OF A', 600, 1145, 24, { role: 'label', color: PALETTE.inkSoft, letterSpacing: 3 }),
      text('LOVE STORY THAT FEELS LIKE HOME', 600, 1230, 44, { role: 'display', color: PALETTE.ink }),
      text('{{couple}} · {{hashtag}}', 600, 1520, 18, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 1 }),
    ],
    decorations: [
      deco('newspaper-masthead-box', { text: 'Wedding Daily', subtext: '{{date}}', layer: 'back' }),
      deco('body-copy', {
        text: '{{couple}} — dua hati yang memilih untuk bertumbuh bersama, hari ini dan setiap hari yang akan datang. {{hashtag}}',
        x: 0.1,
        y: 0.85,
        width: 0.8,
        fontSize: 0.012,
        lineHeight: 1.5,
        color: PALETTE.inkSoft,
        align: 'center',
        layer: 'back',
      }),
    ],
    enabled: true,
  }),

  // 33. Six Grid Memories — GROUP (3x2 grid, 6 photos)
  frame({
    slug: 'six-grid-memories',
    name: 'Six Grid Memories',
    category: 'group',
    description: 'Grid 3×2 untuk enam momen sekaligus.',
    orientation: 'square',
    photoCount: 6,
    canvasWidth: 1200,
    canvasHeight: 850,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(20, 20, 380, 400, { radius: 6 }),
      slot(410, 20, 380, 400, { radius: 6 }),
      slot(800, 20, 380, 400, { radius: 6 }),
      slot(20, 430, 380, 400, { radius: 6 }),
      slot(410, 430, 380, 400, { radius: 6 }),
      slot(800, 430, 380, 400, { radius: 6 }),
    ],
    texts: [],
    decorations: [],
    enabled: true,
  }),

  // 34. Nine Grid Mosaic — GROUP (3x3 grid, 9 photos)
  frame({
    slug: 'nine-grid-mosaic',
    name: 'Nine Grid Mosaic',
    category: 'group',
    description: 'Mosaik 3×3 untuk sembilan momen kecil.',
    orientation: 'square',
    photoCount: 9,
    canvasWidth: 1220,
    canvasHeight: 1220,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: Array.from({ length: 9 }).map((_, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const size = 380;
      const gap = 20;
      return slot(gap + col * (size + gap), gap + row * (size + gap), size, size, { radius: 4 });
    }),
    texts: [],
    decorations: [],
    enabled: true,
  }),

  // 35. Big & Small Grid — GROUP (1 hero + 4 small, asymmetric collage)
  frame({
    slug: 'big-and-small-grid',
    name: 'Big & Small Grid',
    category: 'group',
    description: 'Satu foto besar dikelilingi empat foto kecil.',
    orientation: 'square',
    photoCount: 5,
    canvasWidth: 1200,
    canvasHeight: 1280,
    backgroundColor: PALETTE.ivory,
    accentColor: PALETTE.bronze,
    photoSlots: [
      slot(30, 30, 760, 760, { radius: 8 }),
      slot(810, 30, 360, 360, { radius: 6 }),
      slot(810, 410, 360, 360, { radius: 6 }),
      slot(30, 810, 555, 360, { radius: 6 }),
      slot(605, 810, 565, 360, { radius: 6 }),
    ],
    texts: [text('{{couple}} · {{date}}', 600, 1230, 20, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 })],
    decorations: [],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-01-front-page',
    name: 'Newspaper 01',
    category: 'newspaper',
    description: 'Large hero media, headline, dan dua kolom artikel.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F6F1E6',
    accentColor: PALETTE.ink,
    photoSlots: [slot(90, 310, 1020, 760, { radius: 0 })],
    texts: [
      text('THE EVENT TIMES', 600, 85, 30, { role: 'label', letterSpacing: 5, color: PALETTE.ink }),
      text('{{headline}}', 600, 205, 54, { role: 'display', color: PALETTE.ink }),
      text('{{name}}', 600, 1135, 30, { role: 'label', letterSpacing: 3, color: PALETTE.ink }),
      text('{{eventDate}}', 600, 1185, 18, { role: 'mono', color: PALETTE.inkSoft }),
      text('{{quote}}', 600, 1495, 20, { role: 'display', color: PALETTE.ink }),
    ],
    decorations: [deco('newspaper-rule'), deco('newspaper-columns', { layer: 'back' })],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-02-portrait',
    name: 'Newspaper 02',
    category: 'newspaper',
    description: 'Portrait hero dengan masthead besar dan artikel bawah.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#FBFAF5',
    accentColor: PALETTE.ink,
    photoSlots: [slot(250, 285, 700, 920, { radius: 0 })],
    texts: [
      text('{{name}} JOURNAL', 600, 90, 28, { role: 'label', letterSpacing: 4, color: PALETTE.ink }),
      text('{{headline}}', 600, 220, 42, { role: 'display', color: PALETTE.ink }),
      text('{{subheadline}} · {{eventDate}}', 600, 1320, 18, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [deco('newspaper-masthead-box', { text: 'SPECIAL EVENT', subtext: '{{quote}}', layer: 'back' })],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-strip-04',
    name: 'Newspaper Strip',
    category: 'newspaper',
    description: 'Koran vertikal untuk strip 4 media.',
    orientation: 'strip',
    photoCount: 4,
    canvasWidth: STRIP.w,
    canvasHeight: STRIP.h,
    backgroundColor: '#F5EEDC',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(40, 210, 290, 430, { radius: 0 }),
      slot(370, 210, 290, 430, { radius: 0 }),
      slot(40, 700, 290, 430, { radius: 0 }),
      slot(370, 700, 290, 430, { radius: 0 }),
    ],
    texts: [
      text('WEDDING TIMES', 350, 70, 24, { role: 'label', letterSpacing: 4, color: PALETTE.ink }),
      text('{{headline}}', 350, 145, 28, { role: 'display', color: PALETTE.ink }),
      text('{{name}}', 350, 1235, 24, { role: 'label', letterSpacing: 2, color: PALETTE.ink }),
      text('{{eventDate}}', 350, 1285, 16, { role: 'mono', color: PALETTE.inkSoft }),
      text('{{quote}}', 350, 1985, 20, { role: 'display', color: PALETTE.ink }),
    ],
    decorations: [deco('newspaper-rule'), deco('body-copy', { text: '{{subheadline}}', x: 0.08, y: 0.64, width: 0.84, fontSize: 0.018, lineHeight: 1.45, align: 'center', layer: 'back' })],
    enabled: true,
  }),
  // ==========================================
  // THE DAILY MOMENT — AUTHENTIC NEWSPAPER BROADSHEET
  // ==========================================

  // 1. The Daily Moment — Landscape (Exact Replica of User's Reference)
  frame({
    slug: 'the-daily-moment-landscape',
    name: 'The Daily Moment (Landscape)',
    category: 'newspaper',
    description: 'Halaman depan koran broadsheet horizontal autentik: The Daily Moment — A Day Worth Remembering.',
    orientation: 'landscape',
    photoCount: 1,
    canvasWidth: 1500,
    canvasHeight: 1000,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [slot(345, 275, 810, 640, { radius: 0 })],
    texts: [
      text('A DAY WORTH REMEMBERING', 750, 202, 54, { role: 'display', color: '#211E1B', letterSpacing: 2 }),
      text('Celebrating the people, stories, laughter, and unforgettable moments that make today special.', 750, 246, 20, { role: 'script', color: '#3A322B' }),
      text('Moments Become Memories', 1315, 292, 22, { role: 'display', color: '#211E1B' }),
      text('— PEOPLE MAKE THE NEWS TODAY —', 750, 940, 14, { role: 'label', color: '#4A423A', letterSpacing: 3 }),
      text('"Good moments become great memories."', 185, 905, 16, { role: 'script', color: '#211E1B' }),
      text('"Today\'s photos are tomorrow\'s stories."', 1315, 880, 15, { role: 'script', color: '#211E1B' }),
      text('"Some moments deserve a front page."', 1315, 915, 15, { role: 'script', color: '#211E1B' }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('daily-moment-broadsheet', { text: 'THE DAILY MOMENT', subtext: 'Special Celebration Issue  ·  VOL. 01 — No. 01  ·  {{venue}}' }),
      deco('body-copy', {
        text: 'Some days pass quietly, while others leave a mark we continue to feel for years. Today is one of those rare occasions where familiar faces, warm conversations, spontaneous laughter, and meaningful moments come together in one place. It is not simply about taking photographs or attending a celebration, but about pausing in the feeling of being surrounded by people who matter. Every smile captured today becomes a small piece of history, reminding us that the most valuable memories are often created in ordinary seconds shared with extraordinary people. Long after the decorations are removed and everyone returns home, these photographs will remain as evidence that, on this beautiful day, everyone stopped their busy lives to celebrate, reconnect, laugh together, and create a story worth remembering.',
        x: 0.035,
        y: 0.28,
        width: 0.175,
        fontSize: 0.0125,
        lineHeight: 1.45,
        color: '#211E1B',
      }),
      deco('body-copy', {
        text: 'A photograph can capture a second, but it is the story behind it that lives much longer. Behind every picture taken today are conversations, gentle reunions, nervous smiles, unexpected poses, and people making time for one another. These small connections are what transform an event into a meaningful memory. Years from now, someone may look back at these photographs and remember not only how everyone looked, but also how the room sounded, how the day felt, and who was standing beside them. That is the beauty of documenting a special occasion: it allows one moment to travel far beyond the day itself and become part of a story that can be shared again and again.',
        x: 0.79,
        y: 0.32,
        width: 0.175,
        fontSize: 0.0125,
        lineHeight: 1.45,
        color: '#211E1B',
      }),
    ],
    enabled: true,
  }),

  // 2. The Daily Moment — Duo (Landscape 2 Photos)
  frame({
    slug: 'the-daily-moment-duo',
    name: 'The Daily Moment Duo (2 Foto)',
    category: 'newspaper',
    description: 'Format koran The Daily Moment horizontal dengan 2 foto berdampingan.',
    orientation: 'landscape',
    photoCount: 2,
    canvasWidth: 1500,
    canvasHeight: 1000,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [
      slot(345, 275, 395, 640, { radius: 0 }),
      slot(760, 275, 395, 640, { radius: 0 }),
    ],
    texts: [
      text('A DAY WORTH REMEMBERING', 750, 202, 54, { role: 'display', color: '#211E1B', letterSpacing: 2 }),
      text('Celebrating the people, stories, laughter, and unforgettable moments that make today special.', 750, 246, 20, { role: 'script', color: '#3A322B' }),
      text('Moments Become Memories', 1315, 292, 22, { role: 'display', color: '#211E1B' }),
      text('— PEOPLE MAKE THE NEWS TODAY —', 750, 940, 14, { role: 'label', color: '#4A423A', letterSpacing: 3 }),
      text('"Good moments become great memories."', 185, 905, 16, { role: 'script', color: '#211E1B' }),
      text('"Today\'s photos are tomorrow\'s stories."', 1315, 880, 15, { role: 'script', color: '#211E1B' }),
      text('"Some moments deserve a front page."', 1315, 915, 15, { role: 'script', color: '#211E1B' }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('daily-moment-broadsheet', { text: 'THE DAILY MOMENT', subtext: 'Special Celebration Issue  ·  VOL. 01 — No. 01  ·  {{venue}}' }),
      deco('body-copy', {
        text: 'Some days pass quietly, while others leave a mark we continue to feel for years. Today is one of those rare occasions where familiar faces, warm conversations, spontaneous laughter, and meaningful moments come together in one place. It is not simply about taking photographs or attending a celebration, but about pausing in the feeling of being surrounded by people who matter.',
        x: 0.035,
        y: 0.28,
        width: 0.175,
        fontSize: 0.0125,
        lineHeight: 1.45,
        color: '#211E1B',
      }),
      deco('body-copy', {
        text: 'A photograph can capture a second, but it is the story behind it that lives much longer. Behind every picture taken today are conversations, gentle reunions, nervous smiles, unexpected poses, and people making time for one another. These small connections are what transform an event into a meaningful memory.',
        x: 0.79,
        y: 0.32,
        width: 0.175,
        fontSize: 0.0125,
        lineHeight: 1.45,
        color: '#211E1B',
      }),
    ],
    enabled: true,
  }),

  // 3. The Daily Moment — Portrait (1200 x 1600)
  frame({
    slug: 'the-daily-moment-portrait',
    name: 'The Daily Moment (Portrait)',
    category: 'newspaper',
    description: 'Format koran The Daily Moment vertikal: headline besar, foto utama, dan kolom artikel.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [slot(80, 310, 1040, 720, { radius: 0 })],
    texts: [
      text('A DAY WORTH REMEMBERING', 600, 210, 52, { role: 'display', color: '#211E1B', letterSpacing: 2 }),
      text('Celebrating the people, stories, laughter, and unforgettable moments that make today special.', 600, 255, 18, { role: 'script', color: '#3A322B' }),
      text('— PEOPLE MAKE THE NEWS TODAY —', 600, 1055, 15, { role: 'label', color: '#4A423A', letterSpacing: 3 }),
      text('{{name}}  ·  {{eventDate}}', 600, 1530, 16, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('daily-moment-broadsheet', { text: 'THE DAILY MOMENT', subtext: 'Special Celebration Issue  ·  VOL. 01 — No. 01  ·  {{eventDate}}' }),
      deco('body-copy', {
        text: 'Some days pass quietly, while others leave a mark we continue to feel for years. Today is one of those rare occasions where familiar faces, warm conversations, spontaneous laughter, and meaningful moments come together in one place.',
        x: 0.075,
        y: 0.68,
        width: 0.4,
        fontSize: 0.0125,
        lineHeight: 1.45,
        color: '#211E1B',
      }),
      deco('body-copy', {
        text: 'A photograph can capture a second, but it is the story behind it that lives much longer. Behind every picture taken today are conversations, gentle reunions, nervous smiles, unexpected poses, and people making time for one another.',
        x: 0.525,
        y: 0.68,
        width: 0.4,
        fontSize: 0.0125,
        lineHeight: 1.45,
        color: '#211E1B',
      }),
      deco('body-copy', {
        text: '"Good moments become great memories."  ·  "Today\'s photos are tomorrow\'s stories."',
        x: 0.075,
        y: 0.88,
        width: 0.85,
        fontSize: 0.0135,
        lineHeight: 1.45,
        align: 'center',
        color: '#211E1B',
      }),
      deco('newspaper-columns', { layer: 'back' }),
      deco('qr-code', { color: '#211E1B' }),
      deco('barcode', { color: '#211E1B' }),
    ],
    enabled: true,
  }),

  // NEWSPAPER PHOTO family — one selector, four editorial layouts.
  frame({
    slug: 'newspaper-photo-front-page',
    name: 'NEWSPAPER PHOTO — Front Page Portrait',
    category: 'newspaper',
    description: 'Halaman depan klasik: satu foto utama, headline besar, dan kolom berita.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [slot(90, 320, 1020, 650, { radius: 0 })],
    texts: [
      text('{{headline}}', 600, 220, 54, { role: 'display', color: '#211E1B', maxWidth: 1020, lineHeight: 58 }),
      text('{{name}}', 600, 1010, 25, { role: 'label', color: '#211E1B', letterSpacing: 4 }),
      text('{{eventDate}}  ·  SPECIAL WEDDING EDITION', 600, 1060, 16, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
      text('{{quote}}', 600, 1460, 21, { role: 'display', color: '#211E1B', maxWidth: 950, lineHeight: 26 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: '{{name}} DAILY', subtext: 'Volume 01  ·  No. {{issue}}  ·  {{eventDate}}' }),
      deco('thin-rule', { placement: ['bottom'] }),
      deco('body-copy', { text: '{{article}}', x: 0.075, y: 0.69, width: 0.25, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'A special edition from the happiest corner of the room, printed with gratitude for everyone who made the celebration feel like home.', x: 0.725, y: 0.69, width: 0.2, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('newspaper-columns', { layer: 'back' }),
      deco('qr-code', { color: '#211E1B' }),
    ],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-photo-collage',
    name: 'NEWSPAPER PHOTO — Collage',
    category: 'newspaper',
    description: 'Kolase editorial dengan satu foto utama dan dua potret pendukung.',
    orientation: 'portrait',
    photoCount: 3,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [slot(75, 290, 700, 690, { radius: 0 }), slot(815, 290, 310, 330, { radius: 0 }), slot(815, 650, 310, 330, { radius: 0 })],
    texts: [
      text('{{headline}}', 600, 205, 48, { role: 'display', color: '#211E1B', maxWidth: 1040, lineHeight: 52 }),
      text('THE MAIN STORY', 425, 1015, 19, { role: 'label', color: '#211E1B', letterSpacing: 3 }),
      text('{{name}}  ·  {{eventDate}}', 600, 1510, 17, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: 'THE LOVE TIMES', subtext: 'PHOTO JOURNAL  ·  {{eventDate}}' }),
      deco('body-copy', { text: '{{subheadline}} {{quote}}', x: 0.08, y: 0.66, width: 0.58, fontSize: 0.013, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'Moments from today\'s celebration, filed from the front row.', x: 0.69, y: 0.66, width: 0.23, fontSize: 0.011, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'Memories made today, stories remembered forever. Thank you for being part of our special day.', x: 0.08, y: 0.77, width: 0.84, fontSize: 0.014, lineHeight: 1.45, color: '#211E1B', align: 'center' }),
      deco('newspaper-columns', { layer: 'back' }),
      deco('barcode', { color: '#211E1B' }),
    ],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-photo-breaking-news',
    name: 'NEWSPAPER PHOTO — Breaking News',
    category: 'newspaper',
    description: 'Headline dramatis dengan satu foto utama dan subheadline lebar.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F3EEE3',
    accentColor: '#211E1B',
    photoSlots: [slot(70, 350, 1060, 650, { radius: 0 })],
    texts: [
      text('BREAKING NEWS', 600, 160, 30, { role: 'label', color: '#211E1B', letterSpacing: 7 }),
      text('{{headline}}', 600, 255, 66, { role: 'display', color: '#211E1B', maxWidth: 1080, lineHeight: 68 }),
      text('{{subheadline}}', 600, 1080, 27, { role: 'display', color: '#211E1B', maxWidth: 1020, lineHeight: 32 }),
      text('{{name}}  ·  {{eventDate}}', 600, 1515, 17, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: 'THE WEDDING DAILY', subtext: 'EXTRA  ·  VOLUME 01  ·  NO. 01' }),
      deco('double-rule', { placement: ['top', 'bottom'] }),
      deco('body-copy', { text: '{{quote}} {{subheadline}}', x: 0.08, y: 0.73, width: 0.25, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'Witnesses say the room was full of laughter, happy tears, and the unmistakable feeling of home.', x: 0.72, y: 0.73, width: 0.2, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('qr-code', { color: '#211E1B' }),
    ],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-photo-wedding-daily',
    name: 'NEWSPAPER PHOTO — Wedding Daily',
    category: 'newspaper',
    description: 'Edisi pernikahan romantis untuk satu atau dua foto pasangan.',
    orientation: 'portrait',
    photoCount: 2,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F8F2E7',
    accentColor: '#211E1B',
    photoSlots: [slot(80, 300, 500, 600, { radius: 0 }), slot(620, 300, 500, 600, { radius: 0 })],
    texts: [
      text('A LOVE STORY', 600, 175, 54, { role: 'display', color: '#211E1B', maxWidth: 1000, lineHeight: 58 }),
      text('{{name}}', 600, 965, 30, { role: 'label', color: '#211E1B', letterSpacing: 4 }),
      text('WEDDING DATE  ·  {{eventDate}}  ·  {{venue}}', 600, 1015, 16, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
      text('{{quote}}', 600, 1465, 23, { role: 'display', color: '#211E1B', maxWidth: 940, lineHeight: 28 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: 'THE WEDDING DAILY', subtext: 'SPECIAL WEDDING EDITION  ·  {{eventDate}}' }),
      deco('body-copy', { text: '{{article}}', x: 0.08, y: 0.66, width: 0.84, fontSize: 0.014, lineHeight: 1.5, color: '#211E1B', align: 'center' }),
      deco('body-copy', { text: 'Love wins today — and every day that follows.', x: 0.17, y: 0.79, width: 0.66, fontSize: 0.012, lineHeight: 1.5, color: '#211E1B', align: 'center' }),
      deco('thin-rule', { placement: ['bottom'] }),
      deco('barcode', { color: '#211E1B' }),
    ],
    enabled: true,
  }),
  frame({
    slug: 'newspaper-photo-daily-report',
    name: 'NEWSPAPER PHOTO — Daily Report',
    category: 'newspaper',
    description: 'Complete general newspaper front page with local news, weather, sports, ads and classifieds.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [slot(75, 350, 1050, 560, { radius: 0 })],
    texts: [
      text('{{headline}}', 600, 235, 58, { role: 'display', color: '#211E1B', maxWidth: 1050, lineHeight: 62 }),
      text('PHOTO REPORT  ·  {{eventDate}}  ·  CITY EDITION', 600, 955, 17, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
      text('Photo taken moments before the story went viral.', 600, 1010, 22, { role: 'display', color: '#211E1B', maxWidth: 1000, lineHeight: 27 }),
      text('PAGE 01  ·  VOLUME 01  ·  NO. {{issue}}', 600, 1535, 15, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: '{{name}}', subtext: 'Volume 01  ·  No. {{issue}}  ·  {{eventDate}}  ·  MORNING EDITION' }),
      deco('double-rule', { placement: ['top', 'bottom'] }),
      deco('body-copy', { text: '{{article}} Witnesses say the individual was seen earlier today, appearing unusually confident while posing for the camera. Several people nearby stopped to look, while others described the moment as unexpectedly iconic.', x: 0.075, y: 0.68, width: 0.27, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'LOCAL NEWS  ·  City park reopens after weekend renovation.\n\nCITY UPDATE  ·  Traffic returns to normal after morning delays.\n\nWEATHER  ·  Cloudy morning, partly sunny afternoon, light breeze. 24–31 C. Chance of rain: 35%.', x: 0.37, y: 0.68, width: 0.25, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'SPORTS  ·  Local team celebrates dramatic late win.\n\nENTERTAINMENT  ·  New film draws large weekend crowd.\n\nLIFESTYLE  ·  Why morning coffee remains a daily ritual.\n\nTECHNOLOGY  ·  Digital trends continue to change daily life.', x: 0.66, y: 0.68, width: 0.265, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'TODAY IN NUMBERS  7 cups of coffee  ·  24 photos taken  ·  3 stories worth telling  ·  1 person making headlines', x: 0.075, y: 0.84, width: 0.27, fontSize: 0.011, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'WANTED — LOCAL LEGEND\nLast seen near the photo booth. Highly photogenic. Reward: one unforgettable memory.\n\nCLASSIFIEDS\nFOR SALE: vintage camera. LOST: sunglasses. FOUND: a surprisingly good photo.', x: 0.37, y: 0.84, width: 0.25, fontSize: 0.011, lineHeight: 1.45, color: '#211E1B' }),
      deco('body-copy', { text: 'ADVERTISEMENT\nNeed a better photo? Too late. You already look great.\n\nQUOTE OF THE DAY\n"Every day has a story worth remembering."', x: 0.66, y: 0.84, width: 0.265, fontSize: 0.011, lineHeight: 1.45, color: '#211E1B' }),
      deco('barcode', { color: '#211E1B' }),
      deco('qr-code', { color: '#211E1B' }),
    ],
    enabled: true,
  }),
  // ==========================================
  // MAGAZINE PRESETS (1, 2, 3, 4 Photos)
  // ==========================================

  // Magazine 01 — Full Bleed Solo Cover
  frame({
    slug: 'magazine-01-cover',
    name: 'Magazine Cover (1 Foto)',
    category: 'magazine',
    description: 'Sampul majalah full-media dengan cover lines dan barcode.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: PALETTE.charcoal,
    accentColor: PALETTE.gold,
    photoSlots: [slot(0, 0, 1200, 1600, { radius: 0 })],
    texts: [
      text('{{headline}}', 600, 1340, 52, { role: 'display', color: '#FFFFFF', maxWidth: 1060, lineHeight: 56 }),
      text('{{name}} · {{eventDate}}', 600, 1530, 18, { role: 'mono', color: '#FFFFFF', letterSpacing: 2 }),
    ],
    decorations: [
      deco('dark-vignette'),
      deco('magazine-masthead', { text: '{{name}}', subtext: 'The Wedding Issue', layer: 'front', color: '#FFFFFF' }),
      deco('magazine-cover-lines', { placement: ['left'], color: PALETTE.gold, layer: 'front' }),
      deco('barcode', { color: '#FFFFFF', layer: 'front' }),
    ],
    enabled: true,
  }),

  // Magazine Duo — 2 Photos Editorial
  frame({
    slug: 'magazine-duo-editorial',
    name: 'Magazine Duo (2 Foto)',
    category: 'magazine',
    description: 'Dua foto portrait editorial berdampingan dengan masthead majalah mewah.',
    orientation: 'portrait',
    photoCount: 2,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#FAFAF7',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(60, 220, 520, 940, { radius: 4 }),
      slot(620, 220, 520, 940, { radius: 4 }),
    ],
    texts: [
      text('{{headline}}', 600, 1240, 44, { role: 'display', color: PALETTE.ink, maxWidth: 1040, lineHeight: 48 }),
      text('{{quote}}', 600, 1330, 22, { role: 'display', color: PALETTE.bronze, maxWidth: 960 }),
      text('{{name}} · {{eventDate}} · SPECIAL ISSUE', 600, 1515, 16, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 }),
    ],
    decorations: [
      deco('magazine-masthead', { text: 'EDITORIAL', subtext: 'Special Couple Edition', color: PALETTE.ink }),
      deco('gold-corner', { placement: ['bottom-left', 'bottom-right'], color: PALETTE.gold }),
      deco('barcode', { color: PALETTE.ink }),
      deco('thin-rule', { placement: ['bottom'], color: PALETTE.bronze }),
    ],
    enabled: true,
  }),

  // Magazine Triptych — 3 Photos Collage
  frame({
    slug: 'magazine-triptych-editorial',
    name: 'Magazine Triptych (3 Foto)',
    category: 'magazine',
    description: 'Satu foto utama hero dan dua foto pendukung vertikal ala majalah mode.',
    orientation: 'portrait',
    photoCount: 3,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F8F6F0',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(60, 220, 680, 940, { radius: 4 }),
      slot(770, 220, 370, 455, { radius: 4 }),
      slot(770, 705, 370, 455, { radius: 4 }),
    ],
    texts: [
      text('A STORY OF LOVE & HAPPINESS', 600, 1235, 38, { role: 'display', color: PALETTE.ink, maxWidth: 1020 }),
      text('{{quote}}', 600, 1315, 20, { role: 'display', color: PALETTE.inkSoft, maxWidth: 940 }),
      text('{{name}} · {{eventDate}} · VOLUME 01', 600, 1515, 16, { role: 'mono', color: PALETTE.inkSoft, letterSpacing: 2 }),
    ],
    decorations: [
      deco('magazine-masthead', { text: 'VOGUE STORY', subtext: 'Wedding & Celebration Edition', color: PALETTE.ink }),
      deco('thin-rule', { placement: ['bottom'], color: PALETTE.bronze }),
      deco('barcode', { color: PALETTE.ink }),
    ],
    enabled: true,
  }),

  // Magazine Quad — 4 Photos Lookbook Grid
  frame({
    slug: 'magazine-quad-lookbook',
    name: 'Magazine Quad Lookbook (4 Foto)',
    category: 'magazine',
    description: 'Grid 2x2 elegan bergaya lookbook editorial majalah mode.',
    orientation: 'portrait',
    photoCount: 4,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#FFFFFF',
    accentColor: PALETTE.ink,
    photoSlots: [
      slot(60, 210, 520, 480, { radius: 4 }),
      slot(620, 210, 520, 480, { radius: 4 }),
      slot(60, 720, 520, 480, { radius: 4 }),
      slot(620, 720, 520, 480, { radius: 4 }),
    ],
    texts: [
      text('LOOKBOOK · {{name}}', 600, 1270, 36, { role: 'display', color: PALETTE.ink }),
      text('{{headline}} · {{eventDate}}', 600, 1340, 22, { role: 'label', color: PALETTE.bronze, letterSpacing: 3 }),
      text('{{quote}}', 600, 1495, 18, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [
      deco('magazine-masthead', { text: 'LOOKBOOK', subtext: 'Special 4-Frame Story', color: PALETTE.ink }),
      deco('thin-rule', { placement: ['bottom'], color: PALETTE.bronze }),
      deco('barcode', { color: PALETTE.ink }),
    ],
    enabled: true,
  }),

  // Magazine Strip — 3 Photos Strip
  frame({
    slug: 'magazine-strip-editorial',
    name: 'Magazine Strip (3 Foto)',
    category: 'magazine',
    description: 'Editorial magazine untuk photo strip 3 media.',
    orientation: 'strip',
    photoCount: 3,
    canvasWidth: STRIP.w,
    canvasHeight: STRIP.h,
    backgroundColor: '#FAFAF7',
    accentColor: PALETTE.rose,
    photoSlots: [
      slot(50, 210, 600, 520, { radius: 4 }),
      slot(50, 780, 600, 520, { radius: 4 }),
      slot(50, 1350, 600, 520, { radius: 4 }),
    ],
    texts: [
      text('EDITORIAL', 350, 75, 36, { role: 'label', letterSpacing: 8, color: PALETTE.ink }),
      text('{{headline}}', 350, 140, 26, { role: 'display', color: PALETTE.bronze }),
      text('{{name}} · {{eventDate}}', 350, 1990, 16, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [
      deco('gold-corner', { placement: ['top-left', 'top-right', 'bottom-left', 'bottom-right'], color: PALETTE.gold }),
      deco('thin-rule', { placement: ['top', 'bottom'], color: PALETTE.bronze }),
    ],
    enabled: true,
  }),

  // ==========================================
  // NEWSPAPER PRESETS (1, 2, 3, 4 Photos)
  // ==========================================

  // Newspaper Duo Gazette — 2 Photos
  frame({
    slug: 'newspaper-duo-gazette',
    name: 'Newspaper Duo Gazette (2 Foto)',
    category: 'newspaper',
    description: 'Dua foto berdampingan dalam halaman depan surat kabar lengkap.',
    orientation: 'portrait',
    photoCount: 2,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F6F1E6',
    accentColor: '#211E1B',
    photoSlots: [
      slot(70, 310, 510, 660, { radius: 0 }),
      slot(620, 310, 510, 660, { radius: 0 }),
    ],
    texts: [
      text('{{headline}}', 600, 215, 52, { role: 'display', color: '#211E1B', maxWidth: 1040, lineHeight: 56 }),
      text('THE HAPPY COUPLE  ·  {{eventDate}}  ·  SPECIAL WEDDING EDITION', 600, 1020, 16, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
      text('{{quote}}', 600, 1470, 22, { role: 'display', color: '#211E1B', maxWidth: 940, lineHeight: 28 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: 'THE WEDDING GAZETTE', subtext: 'Volume 01  ·  No. {{issue}}  ·  {{eventDate}}' }),
      deco('body-copy', { text: '{{article}} Surrounded by their beloved family and closest friends, the happy couple shared vows of lifelong commitment and joy.', x: 0.075, y: 0.69, width: 0.4, fontSize: 0.0125, lineHeight: 1.5, color: '#211E1B' }),
      deco('body-copy', { text: 'WEATHER: Bright skies & warm hearts.\nCLASSIFIED: Seeking more dance moves on the floor tonight!', x: 0.55, y: 0.69, width: 0.38, fontSize: 0.012, lineHeight: 1.45, color: '#211E1B' }),
      deco('newspaper-columns', { layer: 'back' }),
      deco('qr-code', { color: '#211E1B' }),
      deco('barcode', { color: '#211E1B' }),
    ],
    enabled: true,
  }),

  // Newspaper Quad Broadsheet — 4 Photos
  frame({
    slug: 'newspaper-quad-broadsheet',
    name: 'Newspaper Quad Broadsheet (4 Foto)',
    category: 'newspaper',
    description: 'Grid 4 foto 2x2 dalam tata letak koran broadsheet klasik.',
    orientation: 'portrait',
    photoCount: 4,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#F5EFE3',
    accentColor: '#211E1B',
    photoSlots: [
      slot(70, 300, 510, 420, { radius: 0 }),
      slot(620, 300, 510, 420, { radius: 0 }),
      slot(70, 750, 510, 420, { radius: 0 }),
      slot(620, 750, 510, 420, { radius: 0 }),
    ],
    texts: [
      text('{{headline}}', 600, 215, 50, { role: 'display', color: '#211E1B', maxWidth: 1040 }),
      text('PHOTO CHRONICLES  ·  {{name}}  ·  {{eventDate}}', 600, 1220, 17, { role: 'mono', color: '#4A423A', letterSpacing: 1 }),
      text('{{quote}}', 600, 1490, 22, { role: 'display', color: '#211E1B', maxWidth: 920 }),
    ],
    decorations: [
      deco('paper-grain', { color: '#4A423A' }),
      deco('newspaper-masthead-box', { text: 'DAILY CHRONICLE', subtext: 'MEMORIES EDITION  ·  {{eventDate}}' }),
      deco('body-copy', { text: 'A visual celebration of today\'s finest moments. Thank you for making this day extraordinary.', x: 0.08, y: 0.81, width: 0.84, fontSize: 0.0135, lineHeight: 1.5, align: 'center', color: '#211E1B' }),
      deco('newspaper-columns', { layer: 'back' }),
      deco('thin-rule', { placement: ['bottom'] }),
      deco('barcode', { color: '#211E1B' }),
    ],
    enabled: true,
  }),

  frame({
    slug: 'birthday-newspaper',
    name: 'Birthday Newspaper',
    category: 'birthday',
    description: 'Koran ulang tahun dengan headline dan quote.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#FFF7E8',
    accentColor: PALETTE.rose,
    photoSlots: [slot(100, 300, 1000, 820, { radius: 0 })],
    texts: [
      text('BIRTHDAY TIMES', 600, 90, 30, { role: 'label', letterSpacing: 5, color: PALETTE.ink }),
      text('{{headline}}', 600, 210, 48, { role: 'display', color: PALETTE.ink }),
      text('{{name}}', 600, 1210, 34, { role: 'label', color: PALETTE.rose, letterSpacing: 3 }),
      text('{{quote}}', 600, 1480, 22, { role: 'display', color: PALETTE.ink }),
    ],
    decorations: [deco('newspaper-rule'), deco('halftone-dots', { placement: ['bottom'], color: PALETTE.rose, layer: 'back' })],
    enabled: true,
  }),
  frame({
    slug: 'corporate-newspaper',
    name: 'Corporate Newspaper',
    category: 'corporate',
    description: 'Template koran untuk event perusahaan.',
    orientation: 'landscape',
    photoCount: 1,
    canvasWidth: LANDSCAPE.w,
    canvasHeight: LANDSCAPE.h,
    backgroundColor: '#F7F7F2',
    accentColor: PALETTE.ink,
    photoSlots: [slot(75, 230, 900, 650, { radius: 0 })],
    texts: [
      text('COMPANY TIMES', 750, 80, 32, { role: 'label', letterSpacing: 6, color: PALETTE.ink }),
      text('{{headline}}', 750, 170, 42, { role: 'display', color: PALETTE.ink }),
      text('{{subheadline}}', 1210, 360, 26, { role: 'display', color: PALETTE.ink }),
      text('{{eventDate}}', 1210, 820, 18, { role: 'mono', color: PALETTE.inkSoft }),
    ],
    decorations: [
      deco('body-copy', {
        text: 'Sebagai perusahaan yang terus berkembang, kami percaya bahwa setiap pencapaian dibangun dari kolaborasi, dedikasi, dan kepercayaan. Melalui inovasi, pelayanan yang konsisten, serta komitmen untuk memberikan dampak positif, kami terus menghadirkan solusi terbaik bagi pelanggan, mitra, dan komunitas. Setiap proyek, tantangan, dan keberhasilan menjadi bagian dari perjalanan bersama menuju masa depan yang lebih kuat dan bermakna.',
        x: 0.68,
        y: 0.45,
        width: 0.24,
        fontSize: 0.022,
        lineHeight: 1.35,
        align: 'left',
        layer: 'back',
      }),
    ],
    enabled: true,
  }),
  frame({
    slug: 'retro-newspaper',
    name: 'Retro Newspaper (1 Foto)',
    category: 'retro',
    description: 'Vintage sepia newspaper broadsheet.',
    orientation: 'portrait',
    photoCount: 1,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#EFE2C4',
    accentColor: '#5A3A1E',
    photoSlots: [slot(120, 330, 960, 800, { radius: 0 })],
    texts: [
      text('RETRO TIMES', 600, 90, 34, { role: 'label', letterSpacing: 6, color: '#5A3A1E' }),
      text('{{headline}}', 600, 220, 48, { role: 'display', color: '#5A3A1E' }),
      text('{{name}} · {{eventDate}}', 600, 1220, 18, { role: 'mono', color: '#5A3A1E', letterSpacing: 2 }),
      text('{{quote}}', 600, 1475, 22, { role: 'display', color: '#5A3A1E' }),
    ],
    decorations: [deco('newspaper-rule')],
    enabled: true,
  }),

  // Retro Duo Cinema (2 Photos)
  frame({
    slug: 'retro-duo-cinema',
    name: 'Retro Duo Cinema (2 Foto)',
    category: 'retro',
    description: 'Dua frame film bioskop retro vintage sepia.',
    orientation: 'portrait',
    photoCount: 2,
    canvasWidth: 1200,
    canvasHeight: 1600,
    backgroundColor: '#3B2A2E',
    accentColor: PALETTE.gold,
    photoSlots: [
      slot(90, 180, 1020, 580, { radius: 6 }),
      slot(90, 800, 1020, 580, { radius: 6 }),
    ],
    texts: [
      text('CINEMATIC ARCHIVE', 600, 90, 28, { role: 'label', letterSpacing: 6, color: PALETTE.gold }),
      text('{{couple}} · {{eventDate}}', 600, 1480, 20, { role: 'mono', color: PALETTE.goldSoft, letterSpacing: 2 }),
    ],
    decorations: [
      deco('film-sprockets', { color: PALETTE.gold }),
      deco('gold-corner', { placement: ['top-left', 'top-right', 'bottom-left', 'bottom-right'], color: PALETTE.gold }),
    ],
    enabled: true,
  }),

  // Retro Sunset Strip (3 Photos)
  frame({
    slug: 'retro-sunset-strip-03',
    name: 'Retro Strip (3 Foto)',
    category: 'retro',
    description: 'Strip 3 foto bernuansa hangat vintage 90s.',
    orientation: 'strip',
    photoCount: 3,
    canvasWidth: STRIP.w,
    canvasHeight: STRIP.h,
    backgroundColor: '#EFE5D1',
    accentColor: '#5A3A1E',
    photoSlots: [
      slot(50, 120, 600, 540, { radius: 6 }),
      slot(50, 720, 600, 540, { radius: 6 }),
      slot(50, 1320, 600, 540, { radius: 6 }),
    ],
    texts: [
      text('RETRO VIBES', 350, 60, 26, { role: 'label', letterSpacing: 5, color: '#5A3A1E' }),
      text('{{couple}} · {{eventDate}}', 350, 1980, 16, { role: 'mono', color: '#5A3A1E' }),
    ],
    decorations: [
      deco('film-sprockets', { color: '#5A3A1E' }),
    ],
    enabled: true,
  }),
];

export function getFrameBySlug(slug: string): FrameConfig | undefined {
  return FRAME_PRESETS.find((f) => f.slug === slug);
}

export const FRAME_CATEGORIES: Array<{ id: FrameConfig['category'] | 'all'; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'newspaper', label: '📰 Newspaper' },
  { id: 'magazine', label: '📸 Magazine' },
  { id: 'retro', label: '🎞️ Retro' },
  { id: 'strip', label: 'Photo Strip' },
  { id: 'signature', label: 'Signature' },
  { id: 'editorial', label: 'Editorial' },
  { id: 'polaroid', label: 'Polaroid' },
  { id: 'classic', label: 'Classic' },
  { id: 'floral', label: 'Floral' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'wedding', label: 'Wedding' },
  { id: 'birthday', label: 'Birthday' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'group', label: 'Group' },
  { id: 'fun', label: 'Fun' },
  { id: 'dark', label: 'Dark' },
];
