import { getSupabaseBrowserClient } from '@/lib/supabase/client';
import { dataUrlToBlob, uploadSessionAsset } from '@/lib/media/upload';
import type { FrameConfig, MediaItem, PhotoMode } from '@/lib/frames/types';
import { queuePendingUpload, removePendingUpload, type QueuedUpload } from '@/lib/media/offlineQueue';

export interface SaveSessionInput {
  guestId: string | null;
  guestName: string | null;
  mode: PhotoMode;
  frame: FrameConfig;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface SaveSessionResult {
  sessionId: string;
  qrToken: string;
}

/**
 * Uploads originals + final + thumbnail to Storage, then writes the
 * photo_sessions / photo_session_assets rows. sessionId/qrToken are
 * generated by the CALLER up front (crypto.randomUUID()) so that a failed
 * attempt can be retried later from the offline queue without producing a
 * duplicate record — retrying just re-runs this with the same ids.
 */
export async function saveSession(
  sessionId: string,
  qrToken: string,
  input: SaveSessionInput,
  finalDataUrl: string,
  thumbnailDataUrl: string,
  mediaItems: MediaItem[]
): Promise<SaveSessionResult> {
  const supabase = getSupabaseBrowserClient();
  const finalBlob = dataUrlToBlob(finalDataUrl);
  const finalIsVideo = finalBlob.type.startsWith('video/');
  const finalExt = finalIsVideo ? (finalBlob.type.includes('mp4') ? 'mp4' : 'webm') : 'jpg';

  // 1. Upload media first — if this throws, no DB rows are written yet,
  // so a retry from the offline queue is always safe.
  await Promise.all(
    mediaItems.map((item, i) => {
      const blob = dataUrlToBlob(item.path);
      const ext = item.type === 'video' ? (blob.type.includes('mp4') ? 'mp4' : 'webm') : 'jpg';
      return uploadSessionAsset(sessionId, `original-${i + 1}.${ext}`, blob, blob.type || (item.type === 'video' ? 'video/webm' : 'image/jpeg'));
    })
  );
  await uploadSessionAsset(sessionId, `final.${finalExt}`, finalBlob, finalBlob.type || (finalIsVideo ? 'video/webm' : 'image/jpeg'));
  await uploadSessionAsset(sessionId, 'thumbnail.jpg', dataUrlToBlob(thumbnailDataUrl), 'image/jpeg');

  // 2. Insert the session. Avoid upsert because public guests intentionally
  // have INSERT access only; a retry verifies the same id/token instead.
  const sessionPayload = {
    id: sessionId,
    guest_id: input.guestId,
    guest_name: input.guestName,
    mode: input.mode,
    frame_id: UUID_RE.test(input.frame.id) ? input.frame.id : null,
    frame_slug: input.frame.slug,
    orientation: input.frame.orientation,
    qr_token: qrToken,
    is_public: true,
  };
  const { error: sessionError } = await supabase.from('photo_sessions').insert(sessionPayload);
  if (sessionError) {
    const { data: existingSession, error: lookupError } = await supabase
      .from('photo_sessions')
      .select('id, qr_token')
      .eq('id', sessionId)
      .eq('qr_token', qrToken)
      .maybeSingle();
    if (lookupError || !existingSession) throw sessionError;
  }

  // 3. Insert asset rows. Delete-then-insert would need an extra
  // permission we don't grant guests, so on retry we rely on the fact
  // that re-uploading with the same storage paths (upsert: true above)
  // and re-inserting metadata rows is harmless duplication at worst —
  // acceptable for a booth retry path. A future admin cleanup pass can
  // dedupe by (session_id, asset_type, shot_index) if ever needed.
  const assetRows = [
    ...mediaItems.map((item, i) => {
      const blob = dataUrlToBlob(item.path);
      const ext = item.type === 'video' ? (blob.type.includes('mp4') ? 'mp4' : 'webm') : 'jpg';
      return {
      session_id: sessionId,
      asset_type: 'original' as const,
      storage_path: `events/yudha-ima/sessions/${sessionId}/original-${i + 1}.${ext}`,
      mime_type: blob.type || (item.type === 'video' ? 'video/webm' : 'image/jpeg'),
      shot_index: i,
    };
    }),
    {
      session_id: sessionId,
      asset_type: 'final' as const,
      storage_path: `events/yudha-ima/sessions/${sessionId}/final.${finalExt}`,
      mime_type: finalBlob.type || (finalIsVideo ? 'video/webm' : 'image/jpeg'),
      shot_index: null,
    },
    {
      session_id: sessionId,
      asset_type: 'thumbnail' as const,
      storage_path: `events/yudha-ima/sessions/${sessionId}/thumbnail.jpg`,
      mime_type: 'image/jpeg',
      shot_index: null,
    },
  ];

  const { data: existingAssets, error: existingAssetsError } = await supabase
    .from('photo_session_assets')
    .select('storage_path')
    .eq('session_id', sessionId);
  if (existingAssetsError) throw existingAssetsError;
  const existingPaths = new Set((existingAssets ?? []).map((asset) => asset.storage_path));
  const missingAssetRows = assetRows.filter((asset) => !existingPaths.has(asset.storage_path));
  if (missingAssetRows.length) {
    const { error: assetsError } = await supabase.from('photo_session_assets').insert(missingAssetRows);
    if (assetsError) throw assetsError;
  }

  await removePendingUpload(sessionId);
  return { sessionId, qrToken };
}

/**
 * Wraps saveSession() so a network failure keeps the render safe on-device
 * (IndexedDB) instead of discarding it, per spec section 43.
 */
export async function saveSessionWithOfflineFallback(
  sessionId: string,
  qrToken: string,
  input: SaveSessionInput,
  finalDataUrl: string,
  thumbnailDataUrl: string,
  mediaItems: MediaItem[]
): Promise<{ ok: true; result: SaveSessionResult } | { ok: false; error: unknown }> {
  try {
    const result = await saveSession(sessionId, qrToken, input, finalDataUrl, thumbnailDataUrl, mediaItems);
    return { ok: true, result };
  } catch (error) {
    await queuePendingUpload({
      sessionId,
      qrToken,
      input,
      finalDataUrl,
      thumbnailDataUrl,
      shotDataUrls: mediaItems.map((item) => item.path),
      mediaItems,
      queuedAt: Date.now(),
    });
    return { ok: false, error };
  }
}

/** Retries a single job pulled from the offline queue (see /gallery-adjacent "upload masih tertunda" UI, or the completion screen's retry button). */
export async function retryQueuedUpload(job: QueuedUpload) {
  return saveSessionWithOfflineFallback(
    job.sessionId,
    job.qrToken,
    job.input,
    job.finalDataUrl,
    job.thumbnailDataUrl,
    job.mediaItems ?? job.shotDataUrls.map((path) => ({ type: 'image' as const, path }))
  );
}
