import { FRAME_PRESETS } from '../src/lib/frames/presets';

function sqlString(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown) {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];
lines.push('-- AUTO-GENERATED by scripts/generate-frame-seed.ts — do not hand-edit.');
lines.push('-- Regenerate with: npx tsx scripts/generate-frame-seed.ts > supabase/migrations/0002_seed_frames.sql');
lines.push('');
lines.push('insert into public.photo_frames');
lines.push('  (name, slug, category, description, orientation, photo_count, configuration, is_active, sort_order)');
lines.push('values');

const rows = FRAME_PRESETS.map((f, i) => {
  const comma = i === FRAME_PRESETS.length - 1 ? '' : ',';
  return `  (${sqlString(f.name)}, ${sqlString(f.slug)}, ${sqlString(f.category)}, ${sqlString(f.description)}, ${sqlString(
    f.orientation
  )}, ${f.photoCount}, ${sqlJson(f)}, true, ${f.sortOrder})${comma}`;
});

lines.push(...rows);
lines.push('');
lines.push('-- Keep frames in sync on re-run without duplicating rows.');
lines.push('on conflict (slug) do update set');
lines.push('  name = excluded.name,');
lines.push('  category = excluded.category,');
lines.push('  description = excluded.description,');
lines.push('  orientation = excluded.orientation,');
lines.push('  photo_count = excluded.photo_count,');
lines.push('  configuration = excluded.configuration,');
lines.push('  sort_order = excluded.sort_order,');
lines.push('  updated_at = now();');

console.log(lines.join('\n'));
