-- Batch 2: additional frames (Magazine Cover, Comic Pop, Newspaper Broadsheet,
-- Retro Sunset Strip, Boho Line Art). Additive/idempotent — safe to re-run.
-- Regenerate full catalog anytime with:
--   npx tsx scripts/generate-frame-seed.ts

insert into public.photo_frames
  (name, slug, category, description, orientation, photo_count, configuration, is_active, sort_order)
values
  ('Magazine Cover', 'magazine-cover', 'editorial', 'Sampul majalah pernikahan lengkap dengan masthead dan barcode.', 'portrait', 1, '{"id":"magazine-cover-26","sortOrder":26,"slug":"magazine-cover","name":"Magazine Cover","category":"editorial","description":"Sampul majalah pernikahan lengkap dengan masthead dan barcode.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1500,"backgroundColor":"#FFFFFF","accentColor":"#2B2620","photoSlots":[{"x":0,"y":200,"width":1200,"height":1300,"radius":0}],"texts":[{"value":"THE WEDDING ISSUE","x":600,"y":150,"size":18,"align":"center","color":"#4A423A","role":"label","letterSpacing":5},{"value":"{{date}}","x":1060,"y":1440,"size":16,"align":"right","color":"#FFFFFF","role":"mono"}],"decorations":[{"kind":"magazine-masthead","text":"Y & I","layer":"back"},{"kind":"barcode","color":"#2B2620","layer":"front"}],"enabled":true}'::jsonb, true, 26),
  ('Comic Pop', 'comic-pop', 'fun', 'Gaya komik pop-art dengan halftone dan speech bubble.', 'square', 1, '{"id":"comic-pop-27","sortOrder":27,"slug":"comic-pop","name":"Comic Pop","category":"fun","description":"Gaya komik pop-art dengan halftone dan speech bubble.","orientation":"square","photoCount":1,"canvasWidth":1200,"canvasHeight":1200,"backgroundColor":"#FFF7E8","accentColor":"#2B2620","photoSlots":[{"x":60,"y":60,"width":1080,"height":1080,"radius":8}],"texts":[],"decorations":[{"kind":"halftone-dots","placement":["bottom"],"color":"#B08281","layer":"back"},{"kind":"speech-bubble","text":"JUST MARRIED!","color":"#2B2620","layer":"front"},{"kind":"comic-burst","text":"LOVE!","color":"#B99A5B","placement":["bottom-right"],"layer":"front"}],"enabled":true}'::jsonb, true, 27),
  ('Newspaper Broadsheet', 'newspaper-broadsheet', 'editorial', 'Tata letak koran lengkap dengan kolom dan headline.', 'portrait', 1, '{"id":"newspaper-broadsheet-28","sortOrder":28,"slug":"newspaper-broadsheet","name":"Newspaper Broadsheet","category":"editorial","description":"Tata letak koran lengkap dengan kolom dan headline.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1500,"backgroundColor":"#F7F4EC","accentColor":"#2B2620","photoSlots":[{"x":70,"y":240,"width":1060,"height":1030,"radius":0}],"texts":[{"value":"YUDHA & IMA GAZETTE","x":600,"y":70,"size":24,"align":"center","color":"#2B2620","role":"label","letterSpacing":3},{"value":"TWO BECOME ONE TODAY","x":600,"y":175,"size":34,"align":"center","color":"#2B2620","role":"display"},{"value":"{{date}} · {{hashtag}}","x":600,"y":1420,"size":16,"align":"center","color":"#4A423A","role":"mono","letterSpacing":1}],"decorations":[{"kind":"newspaper-rule","layer":"back"},{"kind":"newspaper-columns","layer":"back"}],"enabled":true}'::jsonb, true, 28),
  ('Retro Sunset Strip', 'retro-sunset-strip', 'fun', 'Strip 3 foto dengan sentuhan warna retro hangat.', 'strip', 3, '{"id":"retro-sunset-strip-29","sortOrder":29,"slug":"retro-sunset-strip","name":"Retro Sunset Strip","category":"fun","description":"Strip 3 foto dengan sentuhan warna retro hangat.","orientation":"strip","photoCount":3,"canvasWidth":700,"canvasHeight":2100,"backgroundColor":"#3B2A2E","accentColor":"#B99A5B","photoSlots":[{"x":40,"y":40,"width":620,"height":620,"radius":10},{"x":40,"y":690,"width":620,"height":620,"radius":10},{"x":40,"y":1340,"width":620,"height":620,"radius":10}],"texts":[{"value":"{{couple}} · {{hashtag}}","x":350,"y":2015,"size":20,"align":"center","color":"#B99A5B","role":"label","letterSpacing":2}],"decorations":[{"kind":"gold-corner","placement":["top-left","bottom-right"]}],"enabled":true}'::jsonb, true, 29),
  ('Boho Line Art', 'boho-line-art', 'floral', 'Garis floral tipis bergaya boho minimalis.', 'portrait', 1, '{"id":"boho-line-art-30","sortOrder":30,"slug":"boho-line-art","name":"Boho Line Art","category":"floral","description":"Garis floral tipis bergaya boho minimalis.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1500,"backgroundColor":"#EFE3C8","accentColor":"#8A6E4B","photoSlots":[{"x":100,"y":130,"width":1000,"height":1120,"radius":4}],"texts":[{"value":"{{couple}}","x":600,"y":1370,"size":26,"align":"center","color":"#8A6E4B","role":"script"}],"decorations":[{"kind":"floral-border","placement":["top"]},{"kind":"thin-rule","placement":["bottom"]}],"enabled":true}'::jsonb, true, 30)

on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  orientation = excluded.orientation,
  photo_count = excluded.photo_count,
  configuration = excluded.configuration,
  sort_order = excluded.sort_order,
  updated_at = now();
