-- Batch 3: all frames added after the original 25 (magazine/comic/newspaper
-- styles + multi-photo grids). Safe to re-run even if you already ran the
-- earlier 0003_seed_frames_batch2.sql — it will just re-sync those 5 rows
-- with their latest layout fixes (on conflict do update).
-- Regenerate full catalog anytime with:
--   npx tsx scripts/generate-frame-seed.ts

insert into public.photo_frames
  (name, slug, category, description, orientation, photo_count, configuration, is_active, sort_order)
values
  ('Magazine Cover', 'magazine-cover', 'editorial', 'Sampul majalah pernikahan lengkap dengan masthead dan barcode.', 'portrait', 1, '{"id":"magazine-cover-26","sortOrder":26,"slug":"magazine-cover","name":"Magazine Cover","category":"editorial","description":"Sampul majalah pernikahan lengkap dengan masthead dan barcode.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1500,"backgroundColor":"#FFFFFF","accentColor":"#2B2620","photoSlots":[{"x":0,"y":170,"width":1200,"height":1330,"radius":0}],"texts":[{"value":"{{date}}","x":140,"y":1440,"size":16,"align":"left","color":"#FFFFFF","role":"mono"}],"decorations":[{"kind":"magazine-masthead","text":"Y & I","subtext":"The Wedding Issue","layer":"back"},{"kind":"barcode","color":"#2B2620","layer":"front"}],"enabled":true}'::jsonb, true, 26),
  ('Comic Pop', 'comic-pop', 'fun', 'Gaya komik pop-art dengan halftone dan speech bubble.', 'square', 1, '{"id":"comic-pop-27","sortOrder":27,"slug":"comic-pop","name":"Comic Pop","category":"fun","description":"Gaya komik pop-art dengan halftone dan speech bubble.","orientation":"square","photoCount":1,"canvasWidth":1200,"canvasHeight":1200,"backgroundColor":"#FFF7E8","accentColor":"#2B2620","photoSlots":[{"x":60,"y":60,"width":1080,"height":1080,"radius":8}],"texts":[],"decorations":[{"kind":"halftone-dots","placement":["bottom"],"color":"#B08281","layer":"back"},{"kind":"speech-bubble","text":"JUST MARRIED!","color":"#2B2620","layer":"front"},{"kind":"comic-burst","text":"LOVE!","color":"#B99A5B","placement":["bottom-right"],"layer":"front"}],"enabled":true}'::jsonb, true, 27),
  ('Newspaper Broadsheet', 'newspaper-broadsheet', 'editorial', 'Tata letak koran lengkap dengan kolom dan headline.', 'portrait', 1, '{"id":"newspaper-broadsheet-28","sortOrder":28,"slug":"newspaper-broadsheet","name":"Newspaper Broadsheet","category":"editorial","description":"Tata letak koran lengkap dengan kolom dan headline.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1500,"backgroundColor":"#F7F4EC","accentColor":"#2B2620","photoSlots":[{"x":70,"y":240,"width":1060,"height":1030,"radius":0}],"texts":[{"value":"YUDHA & IMA GAZETTE","x":600,"y":70,"size":24,"align":"center","color":"#2B2620","role":"label","letterSpacing":3},{"value":"TWO BECOME ONE TODAY","x":600,"y":175,"size":34,"align":"center","color":"#2B2620","role":"display"},{"value":"{{date}} · {{hashtag}}","x":600,"y":1420,"size":16,"align":"center","color":"#4A423A","role":"mono","letterSpacing":1}],"decorations":[{"kind":"newspaper-rule","layer":"back"},{"kind":"newspaper-columns","layer":"back"}],"enabled":true}'::jsonb, true, 28),
  ('Retro Sunset Strip', 'retro-sunset-strip', 'fun', 'Strip 3 foto dengan sentuhan warna retro hangat.', 'strip', 3, '{"id":"retro-sunset-strip-29","sortOrder":29,"slug":"retro-sunset-strip","name":"Retro Sunset Strip","category":"fun","description":"Strip 3 foto dengan sentuhan warna retro hangat.","orientation":"strip","photoCount":3,"canvasWidth":700,"canvasHeight":2100,"backgroundColor":"#3B2A2E","accentColor":"#B99A5B","photoSlots":[{"x":40,"y":40,"width":620,"height":620,"radius":10},{"x":40,"y":690,"width":620,"height":620,"radius":10},{"x":40,"y":1340,"width":620,"height":620,"radius":10}],"texts":[{"value":"{{couple}} · {{hashtag}}","x":350,"y":2015,"size":20,"align":"center","color":"#B99A5B","role":"label","letterSpacing":2}],"decorations":[{"kind":"gold-corner","placement":["top-left","bottom-right"]}],"enabled":true}'::jsonb, true, 29),
  ('Boho Line Art', 'boho-line-art', 'floral', 'Garis floral tipis bergaya boho minimalis.', 'portrait', 1, '{"id":"boho-line-art-30","sortOrder":30,"slug":"boho-line-art","name":"Boho Line Art","category":"floral","description":"Garis floral tipis bergaya boho minimalis.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1500,"backgroundColor":"#EFE3C8","accentColor":"#8A6E4B","photoSlots":[{"x":100,"y":130,"width":1000,"height":1120,"radius":4}],"texts":[{"value":"{{couple}}","x":600,"y":1370,"size":26,"align":"center","color":"#8A6E4B","role":"script"}],"decorations":[{"kind":"floral-border","placement":["top"]},{"kind":"thin-rule","placement":["bottom"]}],"enabled":true}'::jsonb, true, 30),
  ('Wedding Gazette Cover', 'wedding-gazette-cover', 'editorial', 'Halaman depan koran lengkap: masthead, kolom teks, dan dua foto.', 'portrait', 2, '{"id":"wedding-gazette-cover-31","sortOrder":31,"slug":"wedding-gazette-cover","name":"Wedding Gazette Cover","category":"editorial","description":"Halaman depan koran lengkap: masthead, kolom teks, dan dua foto.","orientation":"portrait","photoCount":2,"canvasWidth":1200,"canvasHeight":1600,"backgroundColor":"#F8F5EC","accentColor":"#2B2620","photoSlots":[{"x":280,"y":260,"width":640,"height":720,"radius":0},{"x":70,"y":1040,"width":280,"height":280,"radius":0}],"texts":[{"value":"TWO HEARTS, ONE STORY","x":600,"y":1010,"size":26,"align":"center","color":"#2B2620","role":"display"},{"value":"{{couple}} · {{date}}","x":600,"y":1490,"size":16,"align":"center","color":"#4A423A","role":"mono","letterSpacing":1},{"value":"SPECIAL EDITION","x":600,"y":1530,"size":14,"align":"center","color":"#4A423A","role":"label","letterSpacing":4}],"decorations":[{"kind":"newspaper-masthead-box","text":"{{couple}} GAZETTE","subtext":"Wedding Edition","layer":"back"},{"kind":"body-copy","text":"Pada hari yang penuh bahagia ini, {{couple}} resmi mengucap janji suci di hadapan keluarga dan sahabat tercinta, mengawali babak baru dalam kisah cinta mereka.","x":0.06,"y":0.175,"width":0.16,"fontSize":0.0125,"lineHeight":1.55,"color":"#2B2620","layer":"back"},{"kind":"body-copy","text":"Dengan restu kedua orang tua serta doa dari semua yang hadir, cinta ini akan terus tumbuh dan menjadi rumah bagi satu sama lain, hari ini dan selamanya.","x":0.78,"y":0.175,"width":0.16,"fontSize":0.0125,"lineHeight":1.55,"color":"#2B2620","layer":"back"},{"kind":"body-copy","text":"{{hashtag}} — abadikan momenmu bersama kami, lalu bagikan ceritamu di album bersama.","x":0.4,"y":0.66,"width":0.54,"fontSize":0.013,"lineHeight":1.5,"color":"#4A423A","layer":"back"}],"enabled":true}'::jsonb, true, 31),
  ('Headline Love Story', 'headline-love-story', 'editorial', 'Judul besar ala cover majalah harian di bawah foto.', 'portrait', 1, '{"id":"headline-love-story-32","sortOrder":32,"slug":"headline-love-story","name":"Headline Love Story","category":"editorial","description":"Judul besar ala cover majalah harian di bawah foto.","orientation":"portrait","photoCount":1,"canvasWidth":1200,"canvasHeight":1600,"backgroundColor":"#FFFFFF","accentColor":"#2B2620","photoSlots":[{"x":60,"y":170,"width":1080,"height":900,"radius":4}],"texts":[{"value":"YOU ARE WORTHY OF A","x":600,"y":1145,"size":24,"align":"center","color":"#4A423A","role":"label","letterSpacing":3},{"value":"LOVE STORY THAT FEELS LIKE HOME","x":600,"y":1230,"size":44,"align":"center","color":"#2B2620","role":"display"},{"value":"{{couple}} · {{hashtag}}","x":600,"y":1520,"size":18,"align":"center","color":"#4A423A","role":"mono","letterSpacing":1}],"decorations":[{"kind":"newspaper-masthead-box","text":"Wedding Daily","subtext":"{{date}}","layer":"back"},{"kind":"body-copy","text":"{{couple}} — dua hati yang memilih untuk bertumbuh bersama, hari ini dan setiap hari yang akan datang. {{hashtag}}","x":0.1,"y":0.85,"width":0.8,"fontSize":0.012,"lineHeight":1.5,"color":"#4A423A","align":"center","layer":"back"}],"enabled":true}'::jsonb, true, 32),
  ('Six Grid Memories', 'six-grid-memories', 'group', 'Grid 3×2 untuk enam momen sekaligus.', 'square', 6, '{"id":"six-grid-memories-33","sortOrder":33,"slug":"six-grid-memories","name":"Six Grid Memories","category":"group","description":"Grid 3×2 untuk enam momen sekaligus.","orientation":"square","photoCount":6,"canvasWidth":1200,"canvasHeight":850,"backgroundColor":"#FFFFFF","accentColor":"#2B2620","photoSlots":[{"x":20,"y":20,"width":380,"height":400,"radius":6},{"x":410,"y":20,"width":380,"height":400,"radius":6},{"x":800,"y":20,"width":380,"height":400,"radius":6},{"x":20,"y":430,"width":380,"height":400,"radius":6},{"x":410,"y":430,"width":380,"height":400,"radius":6},{"x":800,"y":430,"width":380,"height":400,"radius":6}],"texts":[],"decorations":[],"enabled":true}'::jsonb, true, 33),
  ('Nine Grid Mosaic', 'nine-grid-mosaic', 'group', 'Mosaik 3×3 untuk sembilan momen kecil.', 'square', 9, '{"id":"nine-grid-mosaic-34","sortOrder":34,"slug":"nine-grid-mosaic","name":"Nine Grid Mosaic","category":"group","description":"Mosaik 3×3 untuk sembilan momen kecil.","orientation":"square","photoCount":9,"canvasWidth":1220,"canvasHeight":1220,"backgroundColor":"#FFFFFF","accentColor":"#2B2620","photoSlots":[{"x":20,"y":20,"width":380,"height":380,"radius":4},{"x":420,"y":20,"width":380,"height":380,"radius":4},{"x":820,"y":20,"width":380,"height":380,"radius":4},{"x":20,"y":420,"width":380,"height":380,"radius":4},{"x":420,"y":420,"width":380,"height":380,"radius":4},{"x":820,"y":420,"width":380,"height":380,"radius":4},{"x":20,"y":820,"width":380,"height":380,"radius":4},{"x":420,"y":820,"width":380,"height":380,"radius":4},{"x":820,"y":820,"width":380,"height":380,"radius":4}],"texts":[],"decorations":[],"enabled":true}'::jsonb, true, 34),
  ('Big & Small Grid', 'big-and-small-grid', 'group', 'Satu foto besar dikelilingi empat foto kecil.', 'square', 5, '{"id":"big-and-small-grid-35","sortOrder":35,"slug":"big-and-small-grid","name":"Big & Small Grid","category":"group","description":"Satu foto besar dikelilingi empat foto kecil.","orientation":"square","photoCount":5,"canvasWidth":1200,"canvasHeight":1280,"backgroundColor":"#FBF7EF","accentColor":"#8A6E4B","photoSlots":[{"x":30,"y":30,"width":760,"height":760,"radius":8},{"x":810,"y":30,"width":360,"height":360,"radius":6},{"x":810,"y":410,"width":360,"height":360,"radius":6},{"x":30,"y":810,"width":555,"height":360,"radius":6},{"x":605,"y":810,"width":565,"height":360,"radius":6}],"texts":[{"value":"{{couple}} · {{date}}","x":600,"y":1230,"size":20,"align":"center","color":"#4A423A","role":"mono","letterSpacing":2}],"decorations":[],"enabled":true}'::jsonb, true, 35)

on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  orientation = excluded.orientation,
  photo_count = excluded.photo_count,
  configuration = excluded.configuration,
  sort_order = excluded.sort_order,
  updated_at = now();
